### ISSUE TITLE
Demos not working 

### ISSUE THREAD

**Issue by keilw** [hhdevelopment/ocelot-demo#1]
It seems all demos are currently down or the back-end (Websockets) not working.

http://ocelotds.org/demo/chat/chat.html responds:

```
none
Websocket is not ready : status
[]
```

when trying to register a new chatter. 
All other demos also don't do anything.

**Comment by hhfrancois** [comment]
Hi. The angular demo works for me from my phone. I had an error for chat
demo. I will look that quickly.

I will send infos soon.

Thank for trying

Francois Achache

**Comment by hhfrancois** [comment]
Hi Werner
Everything works for me, can you tell me your browser version,
Maybe the javascript console may help me...

Thanks

2015-09-02 18:12 GMT+02:00 françois Achache francois.achache@gmail.com:

> Hi. The angular demo works for me from my phone. I had an error for chat
> demo. I will look that quickly.
> 
> I will send infos soon.
> 
> Thank for trying
> 
> Francois Achache

**Comment by keilw** [comment]
Not even sure, which version of Chrome we have in the office, but at least the one here works.
